package com.projectx.application.backend.entity.model;

import javax.persistence.*;

@Entity
public class BusinessInfo {

    //Setup DB fields for Business Info table
    //Store ID set as autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "store_id")
    private Integer store_id;
    @Column(name = "abn")
    private Integer abn;
    @Column(name = "business_name")
    private String business_name;
    @Column(name = "email_address")
    private String email_address;
    @Column(name = "venue_number")
    private Integer venue_number;


    public BusinessInfo(){
    }

    public Integer getAbn() {

        return abn;
    }

    public void setAbn(Integer ABN) {
        this.abn = ABN;

    }

    public String getBusiness_name() {

        return business_name;
    }

    public void setBusiness_name(String BusinessName) {

        this.business_name = BusinessName;
    }

    public Integer getStore_id() {

        return store_id;
    }

    public void setStore_id(Integer store_id) {

        this.store_id = store_id;
    }

    public String getEmail_address() {

        return email_address;
    }

    public void setEmail_address(String email_address) {

        this.email_address = email_address;
    }

    public Integer getVenue_number() {

        return venue_number;
    }

    public void setVenue_number(Integer venue_number) {
        this.venue_number = venue_number;

    }


}
